name = "back-end"
compatibility_date = "2023-12-01"

node_compat = true
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGY2MjY2NGUtZjlkNC00MDAyLTg2MWQtNmIzNGMzMGJhY2ZlIiwidGVuYW50X2lkIjoiZGZjZDIxZGY1YjMwYmRmNTcyMDE3ZWM5MTM4ZTlkM2FkZDczYjcyYTU3N2YzZTQ2OTgzOTc0OGZlYjVlNThkNyIsImludGVybmFsX3NlY3JldCI6ImM5NDExMGY3LTAwYjctNGY2Mi04NDZjLTEyNjAyMTgxOWYxZSJ9.4f5nYziuSlXwKJJletfhqRrIZvqh7fQMwvIrx5MN7IE"
JWT_SECRET = "myjwtsecret"
